### ISSUE TITLE
Script tag `{'data-component-name': 'ItemDetails'}` not found.

### ISSUE THREAD

**Issue by FRC-95** [Giglium/vinted_scraper#12]
## Describe the bug

Some Vinted website components had changed, including 'data-component-name': 'ItemDetails'

## Steps to reproduce

The _parse_html functions fails (at line 61) because the attrs 'data-component-name': 'ItemDetails' does not longer exist in Vinted website.

## Expected behavior

I'm not an HTML expert, but there doesn't seem to be a tag that directly replaces ItemDetails.

**Comment by Giglium** [comment]
Hi,
you are right they have changed the structure. I've [rerun the tests](https://github.com/Giglium/vinted_scraper/actions/runs/6076785805) and now they fail.

I've checked their source code and the tag `<script type="application/json" data-component-name="ItemDetails">` is missing from the item page. Fortunately, the search is still working.

I will come back at the end of next week to fix it since now I am on holiday.

**Comment by Giglium** [comment]
Hi,
I've fixed the problem with a quick and dirt way. Since the new solution required the API I preferred to implement a quick fix and start rewriting my code to be API-based.  

The new API-based approach (#13) will be a breaking change, I hope it will require a little effort to implement.
