### ISSUE TITLE
How to use instant_buy function ?

### ISSUE THREAD

**Issue by ashlamenace** [Giglium/vinted_scraper#20]
I recently download ur library, and i was able to see a bool instant_buy 
Can i use it to actually instant buy item ? If yes how ?

**Comment by Giglium** [comment]
`instant_buy` is a flag that Vintd added to its Item and I don't know how it works. We only get it from the API response and map it on your object for commodity. 

For now, it's not possible to buy with this package. You can find all the functionality on the [README](https://github.com/Giglium/vinted_scraper#functions).

It's also not easy to implement such logic, because we use the Vinted API and normally the checkout is operated from another external service (this means we need another integration). For this reason, you should create some browser automation, for example with a tool like [Selenium](https://www.selenium.dev/).

**Comment by ashlamenace** [comment]
Thanks for your response, ill do that
