### ISSUE TITLE
Correct usage of search parameters

### ISSUE THREAD

**Issue by Bebio95** [Giglium/vinted_scraper#45]
Hello, you mentioned the following in the search section : 
_Add other query parameters like the pagination and so on_

That sounds interesting but I am a bit confused of **what would the syntax look like to add a parameter** (e.g. add a criteria on a minimum  user rating or a list of specific brands..)

If you could just add a quick example to clarify, it would be very helpful.

Thanks

**Comment by Giglium** [comment]
HI,
the syntax is straightforward, you have a dict and you have to populate it with the params 
````python
params = {
        "search_text": "board games"
        "page": 2 # example for pagination
    }
```
Let me know if this is clear or I will update the `REAMDE.md`.

If you want to know more about how the parameters work, it's a more complex matter. To figure out all the params and how they work is hard, since we don't know how Vinted manages its params. 

For example, if I add `"catalog": 2321` I will filter all the search results by the board games category. how I figure out this? I check the URL after I add the filters that I want on the search page. 

If for example, you want to find criteria on the user rating you should retro-engineering the search page on Vinted to understand how they do it.

**Comment by Bebio95** [comment]
Ok, that's clear enough. Thanks a lot
